export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';

export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';
